spring:
  datasource:
    postgres:
      url: jdbc:postgresql://monorail.proxy.rlwy.net:36820/railway
      username: postgres
      password: daGf2g5fF63dFebDEda*CfBEag3EG-gG
      driver-class-name: org.postgresql.Driver

  jpa:
    postgres:
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
          show_sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    mongodb:
      uri: mongodb+srv://admin:mwjiRZ1nmwvy0z84@cluster0.zryrffw.mongodb.net/vente_voiture?retryWrites=true&w=majority

server:
  port: 8080

jwt:
  tokenLifeSpan: 86400000 # 24 hours in milliseconds
  secretKey: 1qAmtxQAGeIbs8WlvDQiWtxTfJnMqg05ZmkSytTba/NQSMq8eAG+XYQyQ29BkfC
