spring:

   datasource:


      url: jdbc:postgresql://monorail.proxy.rlwy.net:36820/railway
      username: postgres
      password: daGf2g5fF63dFebDEda*CfBEag3EG-gG



      driver-class-name: org.postgresql.Driver
   jpa:
      hibernate:
         ddl-auto: update
      properties:
         hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
            show_sql: true

    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
server:
  port: 8080


jwt:
   tokenLifeSpan: 86400000 # 24 hours in milliseconds
   secretKey: 1qAmtxQAGeIbs8WlvDQiWtxTfJnMqg05ZmkSytTba/NQSMq8eAG+XYQyQ29BkfC
